name: Build Go Binary

on:
  push:
    tags:
      - 'v*' # Trigger on pushes with tags starting with 'v'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Build
        run: go build -o id-generator-${{ matrix.os }}-${{ matrix.arch }} ./api/main.go

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: id-generator-${{ matrix.os }}-${{ matrix.arch }}
          path: id-generator-${{ matrix.os }}-${{ matrix.arch }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: "This is a new release." # Customize your release notes

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: id-generator-${{ matrix.os }}-${{ matrix.arch }}
          file: id-generator-${{ matrix.os }}-${{ matrix.arch }}