name: Build Go Application

on:
  release:
    types: [created]

jobs:
  build:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'  # Specify your desired Go version

      - name: Build the application
        working-directory: ./api  # Change to the directory containing main.go
        run: go build -o id-generator .  # Replace 'myapp' with your desired output name
        with:
          platforms: 'linux/amd64, darwin/amd64, darwin/arm64, windows/amd64'

      - name: Upload Release Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: dist/*
