name: Build Go Binary

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Build
        run: go build -o id-generator ./api/main.go

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: id-generator
          path: id-generator