name: Build Go Binary

on:
  push:
    tags:
      - 'v*' # Trigger on pushes with tags starting with 'v'

jobs:
  build-binaries:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Build
        run: go build -o id-generator-${{ matrix.os }}-${{ matrix.arch }} ./api/main.go

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: id-generator-${{ matrix.os }}-${{ matrix.arch }}
          path: id-generator-${{ matrix.os }}-${{ matrix.arch }}

  build-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        if: matrix.os == 'ubuntu-latest' && matrix.arch == 'arm64'
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Set up Docker Buildx
        run: docker buildx install

      - name: Build Docker Image
        run: |
          docker buildx build --platform=${{ matrix.os }}-amd64,linux/arm64,darwin/arm64 \
            --tag ${{ matrix.os }}-amd64:${{ github.sha }} \
            --tag ${{ matrix.os }}-arm64:${{ github.sha }} \
            --push .
