name: Build Go Binary

on:
  push:
    tags:
      - 'v*' # Trigger on pushes with tags starting with 'v'

jobs:
  build-binaries:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Get Tag Name
        id: tag_name
        run: echo "::set-output name=TAG_NAME::$(echo ${{ github.ref }} | sed 's/refs\/tags\///' | sed 's/\./_/g')"

      - name: Build
        run: go build -o id-generator-${{ steps.tag_name.outputs.TAG_NAME }}-${{ matrix.os }}-${{ matrix.arch }} ./api/main.go

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: id-generator-${{ steps.tag_name.outputs.TAG_NAME }}-${{ matrix.os }}-${{ matrix.arch }}
          path: id-generator-${{ steps.tag_name.outputs.TAG_NAME }}-${{ matrix.os }}-${{ matrix.arch }}

